fix: broken tests due to new filepaths handling
fix: linux AppImage build

chore: remove debug part from release process & clean gitignore files

fix: remaining path issues

chore: minor release permission issue

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,8 +1,6 @@
 name: Release
 
 on:
-  # TODO remove after debug
-  pull_request:
   workflow_dispatch: # manual trigger
 
 permissions:
@@ -31,18 +29,18 @@ jobs:
         with:
           file: "./PKVault.Backend/PKVault.Backend.csproj"
 
-      # - name: Check if version already exist
-      #   env:
-      #     VERSION: v${{ steps.get-version.outputs.version }}
-      #   run: |
-      #     if git ls-remote --tags origin | grep -q "refs/tags/$VERSION"; then
-      #       echo "❌ Error: version $VERSION already exist (tag)!"
-      #       exit 1
-      #     fi
-      #     if gh release list | grep -q "$VERSION"; then
-      #       echo "❌ Error: version $VERSION already exist (release)!"
-      #       exit 1
-      #     fi
+      - name: Check if version already exist
+        env:
+          VERSION: v${{ steps.get-version.outputs.version }}
+        run: |
+          if git ls-remote --tags origin | grep -q "refs/tags/$VERSION"; then
+            echo "❌ Error: version $VERSION already exist (tag)!"
+            exit 1
+          fi
+          if gh release list | grep -q "$VERSION"; then
+            echo "❌ Error: version $VERSION already exist (release)!"
+            exit 1
+          fi
 
       - name: Compute tag and major/minor
         id: compute
@@ -76,35 +74,35 @@ jobs:
           echo "VCS_REF=${GITHUB_SHA}" >> $GITHUB_ENV
           echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
 
-      # - name: Set up Docker Buildx
-      #   uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-      # - name: Login to GHCR
-      #   uses: docker/login-action@v3
-      #   with:
-      #     registry: ghcr.io
-      #     username: ${{ github.actor }}
-      #     password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Login to GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Build and push monolith image
-      #   uses: docker/build-push-action@v6
-      #   with:
-      #     context: .
-      #     file: ./Dockerfile
-      #     target: monolith
-      #     platforms: ${{ matrix.platform }}
-      #     push: true
-      #     tags: |
-      #       ${{ env.REGISTRY_IMAGE_NAME }}:${{ env.TAG }}
-      #       ${{ env.REGISTRY_IMAGE_NAME }}:${{ env.MAJOR_MINOR }}
-      #       ${{ env.REGISTRY_IMAGE_NAME }}:latest
-      #     build-args: |
-      #       VITE_SERVER_URL=http://localhost:3000
-      #       VERSION=${{ env.VERSION }}
-      #       VCS_REF=${{ env.VCS_REF }}
-      #       BUILD_DATE=${{ env.BUILD_DATE }}
-      #     cache-from: type=gha
-      #     cache-to: type=gha,mode=max
+      - name: Build and push monolith image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./Dockerfile
+          target: monolith
+          platforms: ${{ matrix.platform }}
+          push: true
+          tags: |
+            ${{ env.REGISTRY_IMAGE_NAME }}:${{ env.TAG }}
+            ${{ env.REGISTRY_IMAGE_NAME }}:${{ env.MAJOR_MINOR }}
+            ${{ env.REGISTRY_IMAGE_NAME }}:latest
+          build-args: |
+            VITE_SERVER_URL=http://localhost:3000
+            VERSION=${{ env.VERSION }}
+            VCS_REF=${{ env.VCS_REF }}
+            BUILD_DATE=${{ env.BUILD_DATE }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
 
   release:
     name: Create GitHub release
@@ -135,6 +133,7 @@ jobs:
           docker build . --target desktop --build-arg RID=linux-x64 -t tmp-desktop-linux64
           docker create --name tmp-desktop-linux64 tmp-desktop-linux64
           docker cp tmp-desktop-linux64:/app/PKVault.AppImage PKVault.AppImage
+          chmod +x PKVault.AppImage
 
           docker rm tmp-desktop-linux64
           docker rmi tmp-desktop-linux64
@@ -148,16 +147,12 @@ jobs:
           git tag $VERSION
           git push origin $VERSION
 
-      - name: Test desktop files
-        run: |
-          ls -la .
-
-      # - name: Create release
-      #   uses: softprops/action-gh-release@v2
-      #   with:
-      #     tag_name: v${{ env.VERSION }}
-      #     name: v${{ env.VERSION }}
-      #     generate_release_notes: true
-      #     # TODO should include executables from "apps" job
-      #     files: |
-      #       PKVault.exe
+      - name: Create release
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: v${{ env.VERSION }}
+          name: v${{ env.VERSION }}
+          generate_release_notes: true
+          files: |
+            PKVault.exe
+            PKVault.AppImage
